### PR TITLE
add window_title support for xlib

### PR DESCRIPTION
**Pull request by jean-emmanuel**
This PR adds a title to the window created with xlib :)

### CODE REVIEW

**Comment by paddywwoof** [comment]
@jean-emmanuel thanks for this. I'm away at moment but will try to pull this when I get chance.

**Comment by paddywwoof** [comment]
@jean-emmanuel Thanks again. I've pulled the change into the develop branch and updated the github repo https://github.com/tipam/pi3d/commits/develop I had to change the nelements to c_int to get it to match the function definition in xlib.py (Could have changed the 'header' but int seemed to be specified in other refs)

I've also pushed up a version of Texture.update_ndarray() that takes an additional optional argument specifying the GL_TEXTUREn If  you get chance could you check it out for me on your app?

**Comment by jean-emmanuel** [comment]
Awesome, thank you ! The optional argument does the job perfectly.

> I had to change the nelements to c_int

My mistake indeed :)

**Comment by paddywwoof** [comment]
@jean-emmanuel thanks for closing off the other Texture issue. On this title issue I am in the process of swapping to sdl2 which should be able to replace both X11 option and pygame so simplify code and make it more portable. The code is *much* easier using sdl2!

**Comment by jean-emmanuel** [comment]
Great news ! Hopefully this will allow us to have a fullscreen mode :)

**Comment by paddywwoof** [comment]
yes, that was part off the motivation. I srarted to look at doing with libx11 and realised there was a potential to reinvent a load of code already much more expertly implemented in dls2. Also the new RPi4 only implements the nee VC4 gpu driver so there's an incentive to sort this out (it's been on the cards for years). RPi4 also has 4k screen capability which will be interesting for  pictureframe apps.

**Comment by paddywwoof** [comment]
@jean-emmanuel while I get pysdl2 and or pyOpenGL working I patched the X11 setup so fullscreen works: https://github.com/tipam/pi3d/commit/dcd356219e3c20af7c2e871369cc2b98afce4aba
PS liked your music site. You should definitely call in on Tom Swirly if you ever go to Amsterdam! http://tom.swirly.com/index.php?/music/tom-swirly/

**Comment by jean-emmanuel** [comment]
Awesome I'll try it asap !
I'm glad you like it and will keep the name in mind :)

**Comment by jean-emmanuel** [comment]
It works fine, although I'm not sure about the `(w == self.width and h == self.height)` condition's relevance. It could be worth exposing these features as methods, but maybe that's what you had in mind for thd sdl2 version ?

**Comment by paddywwoof** [comment]
Hi, yes definitely. At some stage in the past that had occurred to me but I was so glad to get it working I just stuck it in! Same with the w == self.width etc, it needs thinking through... when the display is initialized width and height are set to the screen dimensions then, at some later stage w and h get set to width and height if they're zero. Very messy and really does need sorting!

I will tidy up the X11 version before releasing as the next version and hopefully be able to carry the improvements on to the sdl2 version later.

**Pull request closed without merging**
