### PR TITLE
Optionally use setuptools

### PR DESCRIPTION
**Pull request by stuaxo**
This lets you do  python setup.py develop  to run pi3d from its dev directory, which can be useful when you are changing things inside it.

### CODE REVIEW

**Comment by paddywwoof** [comment]
Hi, thanks for that. I've just merged that into my local version, develop branch so it will find its way back onto github soon. I will add a comment in the docs.

**Comment by stuaxo** [comment]
Hi,
   Must be that time of year, looking at this again :)
Just wondering why you went with the option of this being something users can comment in, since it should keep the old behaviour if the user only has distutils anyway?

Cheers
S

**Comment by paddywwoof** [comment]
@stuaxo, I did mean to get back and look at this a bit more thoroughly. There was an issue (see #187 with installing pi3d and after trying a couple of things which didn't work I commented it out) I'm needing to move to v2.12 soon so I will try and sort out this problem as well.

@swehner  said there was an error about the ChangeLog file not being there so maybe it's something to do with that - though nothing changed in the setup.py file apart from setuptools stuff as far as I'm aware.

**Comment by stuaxo** [comment]
This is mostly 80% because I'm lazy and don't like to edit it myself :) when I use pi3d.

Hm, the other one is an interesting error - will see if I can repro (though I don't have 3.4 here, just 2.7 and 3.5)...  might be related to recent setuptools changes.

**Comment by stuaxo** [comment]
Urg - So it seems like they broke the old behaviour of MANIFEST for a while, meaning you have to use MANIFEST.in ... until version 3.2.2 when they brought back the old behaviour if a MANIFEST was present.

https://docs.python.org/3/distutils/sourcedist.html#manifest

I added ChangeLog.txt to MANIFEST.in and things seem OK in my fairly unscientific test (compare generated archive and one from pypi).

This one does have extra egg-info folder and the MANIFEST.in, but that is probably correct.

**Comment by stuaxo** [comment]
OK, new version in pull requests - #196

**Pull request closed without merging**
